sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.23.2


before_install:
  - docker-compose up -d --build


deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "shopingMobile"
  env: "shopingmobile-env"
  bucket_name: "elasticbeanstalk-us-east-2-123289027485"
  bucket_path: "shopingMobile"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"